// Bộ tính năng QA nâng cao cho PDF Generator
(function(){
  const $=s=>document.querySelector(s); const enc=new TextEncoder(); const dec=new TextDecoder();
  const form=$('.form-card'); const upload=$('.upload-heading'); if(!form||!upload)return;
  const panel=document.createElement('div'); panel.className='qa-panel'; panel.innerHTML=`
    <div class="section-title"><h2>QA / Test Data nâng cao</h2><span>10 tính năng</span></div>
    <div class="three-col">
      <label><span>Mẫu tài liệu</span><select id="docTemplate"><option value="report">Báo cáo</option><option value="contract">Hợp đồng</option><option value="invoice">Hóa đơn</option><option value="cv">CV / Hồ sơ</option><option value="catalog">Catalog</option><option value="form">Biểu mẫu</option><option value="mixed">Tài liệu hỗn hợp</option></select></label>
      <label><span>Chế độ scan</span><select id="scanMode"><option value="none">PDF thường</option><option value="gray">Scan xám</option><option value="soft">Scan nhẹ</option><option value="bad">Scan xấu / OCR stress</option><option value="mixed">Scan hỗn hợp</option></select></label>
      <label><span>Mật độ bảng</span><select id="tableMode"><option value="none">Không có</option><option value="low">Ít</option><option value="medium">Vừa</option><option value="high">Nhiều</option></select></label>
    </div>
    <div class="three-col">
      <label><span>Header</span><input id="qaHeader" value="TÀI LIỆU KIỂM THỬ" /></label>
      <label><span>Footer</span><input id="qaFooter" value="Generated by PDF QA Tool" /></label>
      <label><span>Watermark</span><input id="qaWatermark" placeholder="SAMPLE / DRAFT / CONFIDENTIAL" /></label>
    </div>
    <div class="three-col">
      <label><span>Random seed</span><input id="qaSeed" type="number" value="123456" /></label>
      <label><span>Chế độ dung lượng</span><select id="sizeMode"><option value="exact">Chính xác</option><option value="range">Ngẫu nhiên trong khoảng</option></select></label>
      <label><span>Batch - số file</span><input id="batchCount" type="number" min="1" max="50" value="5" /></label>
    </div>
    <div id="sizeRangeRow" class="two-col qa-hidden"><label><span>Từ (MB)</span><input id="sizeMin" type="number" value="20" min="1" /></label><label><span>Đến (MB)</span><input id="sizeMax" type="number" value="100" min="1" /></label></div>
    <div class="qa-subtitle">Edge cases</div>
    <div class="toggle-row qa-toggles">
      <label class="toggle"><input id="edgeBlank" type="checkbox"/><span>Trang trắng</span></label>
      <label class="toggle"><input id="edgeRotate" type="checkbox"/><span>Xoay 90°</span></label>
      <label class="toggle"><input id="edgeMixedSize" type="checkbox"/><span>Khổ trang khác nhau</span></label>
      <label class="toggle"><input id="edgeHugeImage" type="checkbox"/><span>Ảnh nặng</span></label>
      <label class="toggle"><input id="edgeTextHeavy" type="checkbox"/><span>Rất nhiều chữ</span></label>
      <label class="toggle"><input id="edgeSpecial" type="checkbox"/><span>Ký tự đặc biệt</span></label>
    </div>
    <div class="qa-subtitle">Preset QA</div>
    <div class="preset-row qa-presets">
      <button type="button" data-preset="small" class="chip">Small 5 MB</button>
      <button type="button" data-preset="large" class="chip">Large 300 MB</button>
      <button type="button" data-preset="huge" class="chip">Huge 1 GB</button>
      <button type="button" data-preset="ocr" class="chip">OCR Stress</button>
      <button type="button" data-preset="image" class="chip">Image Heavy</button>
      <button type="button" data-preset="text" class="chip">Text Heavy</button>
      <button type="button" data-preset="mixed" class="chip">Mixed Document</button>
      <button type="button" data-preset="unicode" class="chip">Unicode Test</button>
    </div>
    <div class="qa-subtitle">Test profile</div>
    <div class="two-col"><label><span>Profile</span><select id="testProfile"><option value="manual">Tùy chỉnh</option><option value="upload">Upload API Stress Test</option><option value="ocr">OCR Pipeline Test</option><option value="viewer">PDF Viewer Stress</option><option value="storage">Storage / CDN Test</option></select></label><div class="ram-card"><span>Ước tính RAM</span><strong id="ramEstimate">~390–510 MB</strong><small id="ramWarning">An toàn trên đa số máy tính</small></div></div>
    <div class="two-col qa-actions"><button type="button" id="batchBtn" class="secondary-action">Tạo batch + ZIP</button><button type="button" id="randomizeBtn" class="secondary-action">Random cấu hình</button></div>`;
  form.insertBefore(panel,upload);

  const origAuto=window.autoText, origLayout=window.layoutFor, origFile=window.fileToJpeg, origBuild=window.buildPdf, origTarget=window.targetBytes;
  function seed(){return Number($('#qaSeed')?.value||123456)>>>0} function rngFor(n=0){let x=(seed()+n*2654435761)>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return (x>>>0)/4294967296}}
  const texts={
    report:['Báo cáo tổng hợp mô phỏng dữ liệu vận hành, tiến độ và các chỉ số kiểm thử hệ thống.','Phần này trình bày kết quả, nhận xét và dữ liệu tham khảo phục vụ đánh giá hiệu năng.'],
    contract:['BÊN A và BÊN B thống nhất các điều khoản, phạm vi công việc, trách nhiệm và điều kiện thực hiện theo tài liệu mẫu này.','Các điều khoản dưới đây chỉ là dữ liệu kiểm thử và không có giá trị pháp lý.'],
    invoice:['HÓA ĐƠN MẪU - Danh sách hàng hóa, số lượng, đơn giá, thuế và tổng giá trị thanh toán được sinh tự động.','Thông tin khách hàng và giao dịch trong tài liệu này hoàn toàn là dữ liệu giả lập.'],
    cv:['HỒ SƠ ỨNG VIÊN - Kinh nghiệm, kỹ năng, dự án và thành tựu được tạo tự động để kiểm thử quy trình xử lý tài liệu.','Thông tin cá nhân trong tài liệu là dữ liệu mẫu.'],
    catalog:['CATALOG SẢN PHẨM - Mỗi trang mô phỏng mô tả sản phẩm, tính năng, thông số và hình ảnh minh họa.','Dữ liệu catalog được sinh ngẫu nhiên phục vụ kiểm thử viewer và storage.'],
    form:['BIỂU MẪU KIỂM THỬ - Họ tên: __________  Mã hồ sơ: __________  Ngày: ____/____/______','Các trường biểu mẫu được tạo để kiểm thử OCR, trích xuất và indexing.'],
    mixed:['Tài liệu hỗn hợp bao gồm văn bản, hình ảnh, bảng và nhiều kiểu bố cục khác nhau để mô phỏng dữ liệu thực tế.','Mục tiêu là kiểm thử upload, preview, OCR, storage, CDN và các pipeline xử lý PDF.']};
  window.autoText=function(page){const tpl=$('#docTemplate')?.value||'report', arr=texts[tpl]||texts.mixed, density=$('#textDensity')?.value||'medium';let n={low:1,medium:2,high:4}[density]||2;if($('#edgeTextHeavy')?.checked)n=8;let out=[];for(let i=0;i<n;i++)out.push(arr[(page+i)%arr.length]);if($('#tableMode')?.value!=='none' && page%({low:5,medium:3,high:2}[$('#tableMode').value]||99)===0)out.push(' | STT | Sản phẩm | SL | Đơn giá | Thành tiền |  1 | Gói kiểm thử A | 2 | 125000 | 250000 |  2 | Gói kiểm thử B | 1 | 320000 | 320000 |');if($('#edgeSpecial')?.checked)out.push(' Special: !@#$%^&*()_+-=[]{};:,.?/\\ <> ~ 0123456789 ABC xyz ');return out.join(' ')};
  window.layoutFor=function(page,hasImage){const m=$('#layoutMode')?.value||'random'; if(m!=='random')return m;if(!hasImage)return'text-only';const r=rngFor(page)();const seq=['text-image','image-text','text-only','text-image'];return seq[Math.floor(r*seq.length)]};

  // Scan mode: can thiệp bước chuyển ảnh sang JPEG.
  if(origFile) window.fileToJpeg=async function(file){const mode=$('#scanMode')?.value||'none';if(mode==='none')return origFile(file);const bmp=await createImageBitmap(file),max=$('#edgeHugeImage')?.checked?3200:1800,s=Math.min(1,max/Math.max(bmp.width,bmp.height)),w=Math.max(1,Math.round(bmp.width*s)),h=Math.max(1,Math.round(bmp.height*s)),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle='#f5f3ea';ctx.fillRect(0,0,w,h);const mixed=mode==='mixed'?(rngFor(w+h)()>.5?'soft':'gray'):mode;ctx.filter=mixed==='gray'?'grayscale(1) contrast(.95)':mixed==='bad'?'grayscale(1) contrast(.78) brightness(1.08) blur(.55px)':'grayscale(.65) contrast(.9)';const angle=(mixed==='bad'?(rngFor(file.size)()-.5)*.05:0);ctx.save();ctx.translate(w/2,h/2);ctx.rotate(angle);ctx.drawImage(bmp,-w/2,-h/2,w,h);ctx.restore();ctx.filter='none';if(mixed==='bad'){ctx.globalAlpha=.08;for(let i=0;i<900;i++){ctx.fillStyle=Math.random()>.5?'#000':'#fff';ctx.fillRect(Math.random()*w,Math.random()*h,1+Math.random()*2,1+Math.random()*2)}ctx.globalAlpha=1}bmp.close();const q=mixed==='bad'?.48:Math.max(.5,Number($('#imageQuality')?.value||82)/100),blob=await new Promise(r=>c.toBlob(r,'image/jpeg',q));return{bytes:new Uint8Array(await blob.arrayBuffer()),width:w,height:h,name:file.name,url:URL.createObjectURL(file)}};

  // Hậu xử lý stream text để chèn header/footer/watermark + một số edge case.
  if(origBuild) window.buildPdf=async function(pageCount,fileName){const result=await origBuild(pageCount,fileName);const header=$('#qaHeader')?.value.trim(),footer=$('#qaFooter')?.value.trim(),water=$('#qaWatermark')?.value.trim();if(!header&&!footer&&!water&&!$('#edgeBlank')?.checked&&!$('#edgeRotate')?.checked&&!$('#edgeMixedSize')?.checked)return result;
    const objParts=result.parts.slice(1,-1), pageObjs=[]; let streamPage=0;
    const esc=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,'?').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
    const changed=objParts.map((p,idx)=>{let s=dec.decode(p);if(/\/Type \/Page\b/.test(s)){pageObjs.push(idx);const pi=pageObjs.length-1;if($('#edgeRotate')?.checked&&pi%7===3)s=s.replace('/MediaBox','/Rotate 90 /MediaBox');if($('#edgeMixedSize')?.checked&&pi%5===4)s=s.replace(/\/MediaBox \[0 0 [^\]]+\]/,'/MediaBox [0 0 612 792]');return enc.encode(s)}if(!/stream\n/.test(s)||/DCTDecode/.test(s))return p;const pi=streamPage++;if($('#edgeBlank')?.checked&&pi%11===7){s=s.replace(/stream\n[\s\S]*?endstream/,'stream\nendstream').replace(/\/Length \d+/,'/Length 0');return enc.encode(s)}let extra='';if(header)extra+=`BT\n/F1 8 Tf\n44 818 Td\n(${esc(header)}) Tj\nET\n`;if(footer)extra+=`BT\n/F1 8 Tf\n44 14 Td\n(${esc(footer)}) Tj\nET\n`;if(water)extra+=`q\n0.82 g\nBT\n/F1 34 Tf\n150 420 Td\n(${esc(water)}) Tj\nET\nQ\n`;if(!extra)return p;const m=s.match(/\/Length (\d+) >>\nstream\n([\s\S]*?)endstream/);if(!m)return p;const body=m[2]+extra;s=s.replace(m[0],`/Length ${enc.encode(body).length} >>\nstream\n${body}endstream`);return enc.encode(s)});
    const headerPart=result.parts[0], parts=[headerPart], offsets=[0];let len=headerPart.length,maxObj=0;for(const p of changed){const m=dec.decode(p.slice(0,30)).match(/(\d+) 0 obj/);if(m){const n=+m[1];maxObj=Math.max(maxObj,n);offsets[n]=len}parts.push(p);len+=p.length}const xrefAt=len;let x=`xref\n0 ${maxObj+1}\n0000000000 65535 f \n`;for(let n=1;n<=maxObj;n++)x+=`${String(offsets[n]||0).padStart(10,'0')} 00000 n \n`;const tail=enc.encode(x+`trailer\n<< /Size ${maxObj+1} /Root 1 0 R >>\nstartxref\n${xrefAt}\n%%EOF\n`);parts.push(tail);return{parts,baseSize:len+tail.length}};

  // Size range bằng cách override targetBytes.
  if(origTarget) window.targetBytes=function(){if($('#sizeMode')?.value!=='range')return origTarget();const min=Number($('#sizeMin')?.value||20),max=Math.max(min,Number($('#sizeMax')?.value||100)),r=rngFor(Date.now()%997)();return Math.round((min+r*(max-min))*1024*1024)};

  function ram(){const count=Math.max(1,Number($('#batchCount')?.value||1)),bytes=(origTarget?origTarget():300*1024*1024),img=$('#metricImages')?Number($('#metricImages').textContent)||0:0,scan=$('#scanMode')?.value!=='none'?1.25:1,estimate=bytes*(1.2+Math.min(.5,img*.03))*scan*count;const mb=estimate/1024/1024;$('#ramEstimate').textContent=mb>1024?`~${(mb/1024).toFixed(1)} GB`:`~${Math.round(mb)} MB`;$('#ramWarning').textContent=mb>1800?'⚠ Nguy cơ tab bị crash':mb>900?'Cần khá nhiều RAM':'An toàn trên đa số máy tính'}
  document.addEventListener('input',e=>{if(panel.contains(e.target)||['targetSize','sizeUnit','pageCount'].includes(e.target.id))ram()});
  $('#sizeMode').onchange=()=>$('#sizeRangeRow').classList.toggle('qa-hidden',$('#sizeMode').value!=='range');

  const presets={small:{size:5,pages:5},large:{size:300,pages:20},huge:{size:1,unit:'gib',pages:50},ocr:{size:100,pages:30,scan:'bad',tpl:'form'},image:{size:300,pages:40,layout:'full-image'},text:{size:100,pages:150,text:'high'},mixed:{size:200,pages:60,tpl:'mixed',table:'medium'},unicode:{size:50,pages:20,special:true}};
  panel.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const p=presets[b.dataset.preset];$('#targetSize').value=p.size;$('#sizeUnit').value=p.unit||'mib';$('#pageCount').value=p.pages; if(p.scan)$('#scanMode').value=p.scan;if(p.tpl)$('#docTemplate').value=p.tpl;if(p.layout)$('#layoutMode').value=p.layout;if(p.text)$('#textDensity').value=p.text;if(p.table)$('#tableMode').value=p.table;if(p.special)$('#edgeSpecial').checked=true;document.dispatchEvent(new Event('input'));ram()});
  $('#testProfile').onchange=()=>{const v=$('#testProfile').value;if(v==='upload'){Object.assign($('#pageCount'),{value:50});$('#sizeMode').value='range';$('#sizeRangeRow').classList.remove('qa-hidden');$('#sizeMin').value=20;$('#sizeMax').value=100;$('#batchCount').value=10}else if(v==='ocr'){$('#scanMode').value='bad';$('#docTemplate').value='form';$('#pageCount').value=80}else if(v==='viewer'){$('#pageCount').value=500;$('#edgeRotate').checked=true;$('#edgeMixedSize').checked=true}else if(v==='storage'){$('#targetSize').value=1;$('#sizeUnit').value='gib';$('#batchCount').value=3}ram()};
  $('#randomizeBtn').onclick=()=>{const r=rngFor(Date.now());$('#qaSeed').value=Math.floor(r()*9999999);$('#pageCount').value=10+Math.floor(r()*190);$('#targetSize').value=10+Math.floor(r()*490);$('#docTemplate').selectedIndex=Math.floor(r()*$('#docTemplate').options.length);$('#layoutMode').selectedIndex=Math.floor(r()*$('#layoutMode').options.length);$('#tableMode').selectedIndex=Math.floor(r()*$('#tableMode').options.length);ram()};

  // ZIP store-only, phù hợp batch test; giới hạn để tránh treo tab.
  const crcTable=(()=>{let t=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
  const crc32=parts=>{let c=0xffffffff;for(const part of parts)for(let i=0;i<part.length;i++)c=crcTable[(c^part[i])&255]^(c>>>8);return(c^0xffffffff)>>>0};
  const le=(n,b)=>{const a=new Uint8Array(b);for(let i=0;i<b;i++)a[i]=(n>>>(8*i))&255;return a};
  async function makeOne(name,bytes){const pc=Math.max(1,Number($('#pageCount').value)||1),r=await window.buildPdf(pc,name);if(r.baseSize>bytes)throw new Error('Nội dung lớn hơn dung lượng mục tiêu');const parts=[...r.parts],chunk=new Uint8Array(8*1024*1024);let left=bytes-r.baseSize;while(left>0){const n=Math.min(left,chunk.length);parts.push(n===chunk.length?chunk:new Uint8Array(n));left-=n}return parts}
  $('#batchBtn').onclick=async()=>{const count=Math.max(1,Math.min(50,Number($('#batchCount').value)||1)),min=$('#sizeMode').value==='range'?Number($('#sizeMin').value||20):Number($('#targetSize').value||10),max=$('#sizeMode').value==='range'?Number($('#sizeMax').value||100):min,unit=$('#sizeUnit').value==='gib'?1024:1,avg=(min+max)/2*unit;if(avg*count>700&&!confirm('Batch ước tính trên 700 MB. Tiếp tục có thể tốn nhiều RAM. Tiếp tục?'))return;const btn=$('#batchBtn');btn.disabled=true;btn.textContent='Đang tạo batch...';try{const files=[];for(let i=0;i<count;i++){const r=rngFor(i+99)(),mb=min+r*(max-min),bytes=Math.round(mb*unit*1024*1024),name=`${($('#fileName').value||'test').replace(/\.pdf$/i,'')}-${String(i+1).padStart(2,'0')}.pdf`;progress?.(Math.round(i/count*80),`Tạo file ${i+1}/${count}`);files.push({name,parts:await makeOne(name,bytes),size:bytes})}const local=[],central=[];let offset=0;for(const f of files){const nb=enc.encode(f.name),crc=crc32(f.parts),lh=[le(0x04034b50,4),le(20,2),le(0,2),le(0,2),le(0,2),le(0,2),le(crc,4),le(f.size,4),le(f.size,4),le(nb.length,2),le(0,2),nb],ls=lh.reduce((n,p)=>n+p.length,0);local.push(...lh,...f.parts);central.push(le(0x02014b50,4),le(20,2),le(20,2),le(0,2),le(0,2),le(0,2),le(0,2),le(crc,4),le(f.size,4),le(f.size,4),le(nb.length,2),le(0,2),le(0,2),le(0,2),le(0,2),le(0,4),le(offset,4),nb);offset+=ls+f.size}const csize=central.reduce((n,p)=>n+p.length,0),end=[le(0x06054b50,4),le(0,2),le(0,2),le(files.length,2),le(files.length,2),le(csize,4),le(offset,4),le(0,2)],blob=new Blob([...local,...central,...end],{type:'application/zip'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='pdf-test-batch.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),60000)}catch(e){alert(e.message)}finally{btn.disabled=false;btn.textContent='Tạo batch + ZIP';ram()}};
  ram();
})();
