// Đồng bộ giao diện và ý nghĩa: cấu hình nâng cao áp dụng trực tiếp vào PDF chính; tạo hàng loạt là khu vực riêng.
(function () {
  const $ = (s, root = document) => root.querySelector(s);
  const panel = $('.qa-panel');
  const form = $('.form-card');
  if (!panel || !form) return;

  // 1) Việt hóa và làm rõ phần cấu hình nâng cao.
  const title = $('.section-title h2', panel);
  if (title) title.textContent = 'Công cụ kiểm thử nâng cao';
  const titleMeta = $('.section-title span', panel);
  if (titleMeta) titleMeta.textContent = 'Áp dụng vào PDF chính';

  const note = document.createElement('div');
  note.className = 'qa-apply-note';
  note.innerHTML = '<strong>Mọi tùy chọn bên dưới sẽ được áp dụng trực tiếp vào file PDF khi bấm “Tạo PDF”.</strong><span>Ví dụ: scan xấu, bảng, watermark, trang trắng, xoay trang, Unicode… đều nằm trong chính file đang cấu hình phía trên.</span>';
  const firstTitle = $('.section-title', panel);
  firstTitle?.insertAdjacentElement('afterend', note);

  const renameText = [
    ['Random seed', 'Mã tái tạo ngẫu nhiên'],
    ['Header', 'Đầu trang'],
    ['Footer', 'Chân trang'],
    ['Watermark', 'Dấu chìm'],
    ['Edge cases', 'Tình huống kiểm thử đặc biệt'],
    ['Preset QA', 'Cấu hình kiểm thử có sẵn'],
    ['Test profile', 'Kịch bản kiểm thử'],
    ['Profile', 'Kịch bản'],
    ['Batch - số file', 'Số file tạo hàng loạt']
  ];
  panel.querySelectorAll('span,.qa-subtitle').forEach(el => {
    const text = el.textContent.trim();
    const found = renameText.find(([from]) => text === from);
    if (found) el.textContent = found[1];
  });

  const watermark = $('#qaWatermark');
  if (watermark) watermark.placeholder = 'MẪU / BẢN NHÁP / BẢO MẬT';
  const footer = $('#qaFooter');
  if (footer && footer.value === 'Generated by PDF QA Tool') footer.value = 'Được tạo bởi công cụ kiểm thử PDF';

  const labels = {
    small: 'File nhỏ 5 MB',
    large: 'File lớn 300 MB',
    huge: 'File rất lớn 1 GB',
    ocr: 'Kiểm thử OCR',
    image: 'Nhiều hình ảnh',
    text: 'Nhiều văn bản',
    mixed: 'Tài liệu hỗn hợp',
    unicode: 'Kiểm thử Unicode'
  };
  panel.querySelectorAll('[data-preset]').forEach(btn => {
    if (labels[btn.dataset.preset]) btn.textContent = labels[btn.dataset.preset];
  });

  const profile = $('#testProfile');
  if (profile) {
    const map = {
      manual: 'Tùy chỉnh',
      upload: 'Kiểm thử tải lên API',
      ocr: 'Kiểm thử quy trình OCR',
      viewer: 'Kiểm thử trình xem PDF',
      storage: 'Kiểm thử lưu trữ / CDN'
    };
    [...profile.options].forEach(o => { if (map[o.value]) o.textContent = map[o.value]; });
  }

  const scan = $('#scanMode');
  if (scan) {
    const map = { none: 'PDF thông thường', gray: 'Bản quét xám', soft: 'Bản quét nhẹ', bad: 'Bản quét xấu / thử OCR', mixed: 'Bản quét hỗn hợp' };
    [...scan.options].forEach(o => { if (map[o.value]) o.textContent = map[o.value]; });
  }

  // 2) Tách toàn bộ phần tạo hàng loạt thành khu vực riêng.
  const batchCount = $('#batchCount');
  const batchBtn = $('#batchBtn');
  if (batchCount && batchBtn) {
    const batchSection = document.createElement('div');
    batchSection.className = 'batch-section';
    batchSection.innerHTML = `
      <div class="section-title"><h2>Tạo nhiều file cùng lúc</h2><span>Tùy chọn riêng</span></div>
      <div class="batch-note">Phần này chỉ dùng khi bạn muốn sinh nhiều PDF từ cùng cấu hình và tải xuống dưới dạng ZIP. Không cần dùng nếu chỉ tạo một file PDF.</div>
      <div class="two-col batch-grid">
        <label><span>Số file</span><div id="batchCountSlot"></div></label>
        <div class="batch-action-slot" id="batchBtnSlot"></div>
      </div>`;
    panel.insertAdjacentElement('afterend', batchSection);
    $('#batchCountSlot', batchSection)?.appendChild(batchCount);
    $('#batchBtnSlot', batchSection)?.appendChild(batchBtn);
    batchBtn.textContent = 'Tạo nhiều PDF và tải ZIP';

    // Xóa ô/nhãn cũ bị trống sau khi di chuyển.
    panel.querySelectorAll('label').forEach(label => {
      if (!label.querySelector('input,select,textarea') && !label.textContent.trim()) label.remove();
      if (!label.querySelector('input,select,textarea') && /Số file tạo hàng loạt/.test(label.textContent)) label.remove();
    });
  }

  // 3) Random cấu hình chỉ thay đổi cấu hình của PDF chính.
  const randomBtn = $('#randomizeBtn');
  if (randomBtn) randomBtn.textContent = 'Tạo cấu hình ngẫu nhiên cho PDF';

  // 4) Nhấn Tạo PDF: hiển thị tóm tắt cấu hình nâng cao đang được áp dụng.
  const generate = $('#generateBtn');
  if (generate) {
    let summary = $('#advancedApplySummary');
    if (!summary) {
      summary = document.createElement('div');
      summary.id = 'advancedApplySummary';
      summary.className = 'advanced-apply-summary';
      generate.insertAdjacentElement('beforebegin', summary);
    }
    const updateSummary = () => {
      const parts = [];
      const template = $('#docTemplate');
      const scanMode = $('#scanMode');
      const table = $('#tableMode');
      const wm = $('#qaWatermark');
      if (template) parts.push(`Mẫu: ${template.options[template.selectedIndex]?.text || ''}`);
      if (scanMode && scanMode.value !== 'none') parts.push(`Quét: ${scanMode.options[scanMode.selectedIndex]?.text || ''}`);
      if (table && table.value !== 'none') parts.push(`Bảng: ${table.options[table.selectedIndex]?.text || ''}`);
      if (wm?.value.trim()) parts.push(`Dấu chìm: ${wm.value.trim()}`);
      const special = [
        ['edgeBlank', 'trang trắng'], ['edgeRotate', 'xoay trang'], ['edgeMixedSize', 'khổ trang khác nhau'],
        ['edgeHugeImage', 'ảnh nặng'], ['edgeTextHeavy', 'nhiều chữ'], ['edgeSpecial', 'ký tự đặc biệt']
      ].filter(([id]) => document.getElementById(id)?.checked).map(([,n]) => n);
      if (special.length) parts.push(`Đặc biệt: ${special.join(', ')}`);
      summary.textContent = parts.length ? `Sẽ áp dụng vào PDF: ${parts.join(' • ')}` : 'PDF sẽ dùng cấu hình tiêu chuẩn.';
    };
    panel.addEventListener('input', updateSummary);
    panel.addEventListener('change', updateSummary);
    updateSummary();
  }
})();
