// Đồng bộ giao diện: chỉ còn một nút hành động chính để tạo PDF hoặc tạo hàng loạt.
(function () {
  const $ = (s, root = document) => root.querySelector(s);
  const panel = $('.qa-panel');
  const form = $('.form-card');
  if (!panel || !form) return;

  // Việt hóa và làm rõ phần cấu hình nâng cao.
  const title = $('.section-title h2', panel);
  if (title) title.textContent = 'Công cụ kiểm thử nâng cao';
  const titleMeta = $('.section-title span', panel);
  if (titleMeta) titleMeta.textContent = 'Áp dụng vào PDF chính';

  const note = document.createElement('div');
  note.className = 'qa-apply-note';
  note.innerHTML = '<strong>Mọi tùy chọn bên dưới sẽ được áp dụng trực tiếp vào file PDF.</strong><span>Ví dụ: bản quét xấu, bảng, dấu chìm, trang trắng, xoay trang, Unicode… đều nằm trong chính file đang cấu hình.</span>';
  $('.section-title', panel)?.insertAdjacentElement('afterend', note);

  const renameText = [
    ['Random seed', 'Mã tái tạo ngẫu nhiên'],
    ['Header', 'Đầu trang'],
    ['Footer', 'Chân trang'],
    ['Watermark', 'Dấu chìm'],
    ['Edge cases', 'Tình huống kiểm thử đặc biệt'],
    ['Preset QA', 'Cấu hình kiểm thử có sẵn'],
    ['Test profile', 'Kịch bản kiểm thử'],
    ['Profile', 'Kịch bản'],
    ['Batch - số file', 'Số file tạo hàng loạt']
  ];
  panel.querySelectorAll('span,.qa-subtitle').forEach(el => {
    const found = renameText.find(([from]) => el.textContent.trim() === from);
    if (found) el.textContent = found[1];
  });

  const watermark = $('#qaWatermark');
  if (watermark) watermark.placeholder = 'MẪU / BẢN NHÁP / BẢO MẬT';
  const footer = $('#qaFooter');
  if (footer && footer.value === 'Generated by PDF QA Tool') footer.value = 'Được tạo bởi công cụ kiểm thử PDF';

  const presetLabels = {
    small: 'File nhỏ 5 MB', large: 'File lớn 300 MB', huge: 'File rất lớn 1 GB',
    ocr: 'Kiểm thử OCR', image: 'Nhiều hình ảnh', text: 'Nhiều văn bản',
    mixed: 'Tài liệu hỗn hợp', unicode: 'Kiểm thử Unicode'
  };
  panel.querySelectorAll('[data-preset]').forEach(btn => {
    if (presetLabels[btn.dataset.preset]) btn.textContent = presetLabels[btn.dataset.preset];
  });

  const profile = $('#testProfile');
  if (profile) {
    const map = {manual:'Tùy chỉnh',upload:'Kiểm thử tải lên API',ocr:'Kiểm thử quy trình OCR',viewer:'Kiểm thử trình xem PDF',storage:'Kiểm thử lưu trữ / CDN'};
    [...profile.options].forEach(o => { if (map[o.value]) o.textContent = map[o.value]; });
  }
  const scan = $('#scanMode');
  if (scan) {
    const map = {none:'PDF thông thường',gray:'Bản quét xám',soft:'Bản quét nhẹ',bad:'Bản quét xấu / thử OCR',mixed:'Bản quét hỗn hợp'};
    [...scan.options].forEach(o => { if (map[o.value]) o.textContent = map[o.value]; });
  }

  // Tạo hàng loạt trở thành một chế độ, không còn nút tạo riêng.
  const batchCount = $('#batchCount');
  const batchBtn = $('#batchBtn');
  const generate = $('#generateBtn');
  let batchToggle = null;

  if (batchCount && batchBtn && generate) {
    const batchSection = document.createElement('div');
    batchSection.className = 'batch-section compact-batch';
    batchSection.innerHTML = `
      <div class="section-title"><h2>Tạo nhiều file cùng lúc</h2><span>Tùy chọn</span></div>
      <label class="batch-enable-row">
        <span class="batch-toggle-copy"><strong>Tạo hàng loạt</strong><small>Bật để nút “Tạo PDF” phía dưới chuyển sang tạo nhiều PDF và tải ZIP.</small></span>
        <input id="batchEnabled" type="checkbox" />
      </label>
      <div id="batchOptions" class="batch-options hidden">
        <label><span>Số file</span><div id="batchCountSlot"></div></label>
      </div>`;
    panel.insertAdjacentElement('afterend', batchSection);
    $('#batchCountSlot', batchSection)?.appendChild(batchCount);
    batchToggle = $('#batchEnabled', batchSection);
    const batchOptions = $('#batchOptions', batchSection);

    // Nút batch cũ vẫn giữ lại để dùng logic sẵn có, nhưng ẩn khỏi UI.
    batchBtn.classList.add('hidden');
    batchBtn.setAttribute('aria-hidden', 'true');

    // Dọn nhãn cũ sau khi chuyển input ra ngoài.
    panel.querySelectorAll('label').forEach(label => {
      if (!label.querySelector('input,select,textarea') && /Số file tạo hàng loạt|Batch/.test(label.textContent)) label.remove();
    });

    const syncPrimaryAction = () => {
      const enabled = !!batchToggle.checked;
      batchOptions.classList.toggle('hidden', !enabled);
      const count = Math.max(1, Number(batchCount.value || 1));
      generate.textContent = enabled ? `Tạo ${count} PDF và tải ZIP` : 'Tạo PDF';
      generate.classList.toggle('batch-primary', enabled);
    };
    batchToggle.addEventListener('change', syncPrimaryAction);
    batchCount.addEventListener('input', syncPrimaryAction);
    syncPrimaryAction();

    // Nếu đang bật hàng loạt, dùng duy nhất nút chính để gọi logic batch hiện có.
    generate.addEventListener('click', (event) => {
      if (!batchToggle.checked) return;
      event.preventDefault();
      event.stopImmediatePropagation();
      batchBtn.click();
    }, true);
  }

  // Nút tạo cấu hình ngẫu nhiên chỉ là công cụ cấu hình, không phải nút tạo file.
  const randomBtn = $('#randomizeBtn');
  if (randomBtn) randomBtn.textContent = 'Ngẫu nhiên cấu hình';

  // Tóm tắt cấu hình đang áp dụng ngay trước nút tạo duy nhất.
  if (generate) {
    let summary = $('#advancedApplySummary');
    if (!summary) {
      summary = document.createElement('div');
      summary.id = 'advancedApplySummary';
      summary.className = 'advanced-apply-summary';
      generate.insertAdjacentElement('beforebegin', summary);
    }
    const updateSummary = () => {
      const parts = [];
      const template = $('#docTemplate');
      const scanMode = $('#scanMode');
      const table = $('#tableMode');
      const wm = $('#qaWatermark');
      if (template) parts.push(`Mẫu: ${template.options[template.selectedIndex]?.text || ''}`);
      if (scanMode && scanMode.value !== 'none') parts.push(`Quét: ${scanMode.options[scanMode.selectedIndex]?.text || ''}`);
      if (table && table.value !== 'none') parts.push(`Bảng: ${table.options[table.selectedIndex]?.text || ''}`);
      if (wm?.value.trim()) parts.push(`Dấu chìm: ${wm.value.trim()}`);
      const special = [
        ['edgeBlank','trang trắng'],['edgeRotate','xoay trang'],['edgeMixedSize','khổ trang khác nhau'],
        ['edgeHugeImage','ảnh nặng'],['edgeTextHeavy','nhiều chữ'],['edgeSpecial','ký tự đặc biệt']
      ].filter(([id]) => document.getElementById(id)?.checked).map(([,n]) => n);
      if (special.length) parts.push(`Đặc biệt: ${special.join(', ')}`);
      if (batchToggle?.checked) parts.push(`Tạo hàng loạt: ${Math.max(1, Number(batchCount?.value || 1))} file`);
      summary.textContent = parts.length ? `Sẽ áp dụng: ${parts.join(' • ')}` : 'PDF sẽ dùng cấu hình tiêu chuẩn.';
    };
    form.addEventListener('input', updateSummary);
    form.addEventListener('change', updateSummary);
    updateSummary();
  }
})();
